[project]
name = "nerdvana"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.15.2",
    "fastapi[standard]>=0.115.12",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.0",
]
